/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package uk.ac.manchester.cs.sushifinder;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
/**
 *
 * @author Hani Al Abbas
 */
public class MainJFrame extends JFrame {

 /*   JMenuBar menuBar;
    JMenu file;
    JMenuItem importOntology, about, */
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setTitle("The Manchester Sushi Finder");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        //this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setSize(800, 600);
        this.setResizable(false);
        this.setLocation((dim.width-this.getSize().width)/2, (dim.height-this.getSize().height)/2);
        /*menuBar = new JMenuBar();
        file = new JMenu("File");
        menuBar.add(file);
        this.setJMenuBar(menuBar);*/
        
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */                        
    private void initComponents() {
        
        sp = new StartPanel();
        sp.setBorder(BorderFactory.createLineBorder(Color.black));
        sp.setVisible(true);
        this.add(sp);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        
        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify 
    StartPanel sp;
    // End of variables declaration                   
}
