/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package uk.ac.manchester.cs.sushifinder;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author machdd
 */
public class StartPanel extends JPanel {

    /**
     * Creates new form NewJPanel
     */
    public StartPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                        
    private void initComponents() {

        label = new JLabel("Welcome to The Manchester Sushi Finder");
        //setSize(800, 400);
        this.setBackground(Color.red);
        label.setFont(new Font("Lucida Grande", 0, 18));
        this.add(label, BorderLayout.CENTER);
        
    }                     


    // Variables declaration - do not modify 
    private JLabel label;
    // End of variables declaration                   
}
